[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:vnc]
priority=10
command=/usr/sbin/gosu ubuntu /home/ubuntu/.vnc/vnc_run.sh
autorestart=true
stdout_logfile=/tmp/supervisor-vnc.log
stderr_logfile=/tmp/supervisor-vnc.err.log

[program:novnc]
priority=20
command=/usr/sbin/gosu ubuntu websockify --web=/usr/share/novnc 80 localhost:5901
autorestart=true
stdout_logfile=/tmp/supervisor-novnc.log
stderr_logfile=/tmp/supervisor-novnc.err.log
